Description: Create a CodePipeline pipeline to buuld and deploy Agent Event viewer

Parameters:
  CodeCommitRepository:
    Type: String
    Description: Name of the CodeCommit repository that contains the application
  BranchName:
    Type: String
    Description: Name of the branch in CodeCommit repository
  ArtifactStoreS3Location:
    Type: String
    Description: Name of the S3 bucket to store CodePipeline artificat

Resources:
  CodePipelineRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName:
        Fn::Sub: CodePipelineRole-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "codepipeline.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        -
          PolicyName: "AgentEventViewerCodePipelinePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "s3:DeleteObject"
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:ListBucket"
                  - "s3:PutObject"
                  - "s3:GetBucketPolicy"
                Resource:
                  - Fn::Sub: arn:aws:s3:::${ArtifactStoreS3Location}
                  - Fn::Sub: arn:aws:s3:::${ArtifactStoreS3Location}/*
              -
                Effect: "Allow"
                Action:
                  - "codecommit:ListBranches"
                  - "codecommit:ListRepositories"
                  - "codecommit:BatchGetRepositories"
                  - "codecommit:Get*"
                  - "codecommit:GitPull"
                  - "codecommit:UploadArchive"
                Resource:
                  - Fn::Sub: arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${CodeCommitRepository}
              -
                Effect: "Allow"
                Action:
                  - "cloudformation:*"
                Resource:
                  - Fn::Sub: arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/AgentEventProcessor-${AWS::StackName}*
                  - Fn::Sub: arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/AgentEventViewerHosting-${AWS::StackName}*
              -
                Effect: "Allow"
                Action:
                  - "codebuild:StartBuild"
                  - "codebuild:BatchGetBuilds"
                Resource:
                  - Fn::Sub: arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/AgentEventProcessor-${AWS::StackName}
                  - Fn::Sub: arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/AgentEventViewerHosting-${AWS::StackName}
                  - Fn::Sub: arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/AgentEventViewer-${AWS::StackName}
              -
                Effect: "Allow"
                Action:
                  - "iam:PassRole"
                Resource:
                  - Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/CloudFormationRole-${AWS::StackName}

  CloudFormationRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName:
        Fn::Sub: CloudFormationRole-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "cloudformation.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        -
          PolicyName: "CloudFormationAgentEventViewerStackPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "iam:*"
                Resource:
                  - "*"
              -
                Effect: "Allow"
                Action:
                  - "s3:*"
                  - "kinesis:*"
                  - "apigateway:*"
                  - "lambda:*"
                  - "cloudfront:*"
                  - "dynamodb:*"
                  - "cloudformation:*"
                Resource:
                  - "*"
  CodeBuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName:
        Fn::Sub: CodeBuildRole-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /service-role/
      Policies:
        -
          PolicyName: "CodeBuildAgentEventViewerPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "cloudformation:*"
                Resource:
                  - "*"
              -
                Effect: "Allow"
                Action:
                  - "codecommit:ListBranches"
                  - "codecommit:ListRepositories"
                  - "codecommit:BatchGetRepositories"
                  - "codecommit:Get*"
                  - "codecommit:GitPull"
                Resource:
                  - Fn::Sub: arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${CodeCommitRepository}
              -
                Effect: "Allow"
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:ListBucket"
                  - "codepipeline:*"
                  - "logs:*"
                Resource:
                  - "*"
  AgentEventProcessorBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name:
        Fn::Sub: AgentEventProcessor-${AWS::StackName}
      Description: Build Agent Event Processor 
      ServiceRole:
        Fn::GetAtt: [ CodeBuildRole, Arn ]
      Artifacts:
        Type: CODEPIPELINE
        Name: 
          Fn::Sub: AgentEventProcessor-${AWS::StackName}
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        EnvironmentVariables:
          - Name: BUILD_OUTPUT_BUCKET
            Value:
              Ref: ArtifactStoreS3Location
      Source:
        Type: CODEPIPELINE
        BuildSpec: agent-event-processor/buildspec.yml
        InsecureSsl: false
      TimeoutInMinutes: 60
      EncryptionKey:
        Fn::Sub: arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED

  AgentEventViewerHostingBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name:
        Fn::Sub: AgentEventViewerHosting-${AWS::StackName}
      Description: Build Agent Event Viewer Hosting environment
      ServiceRole:
        Fn::GetAtt: [ CodeBuildRole, Arn ]
      Artifacts:
        Type: CODEPIPELINE
        Name: 
          Fn::Sub: AgentEventViewerHosting-${AWS::StackName}
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        EnvironmentVariables:
          - Name: BUILD_OUTPUT_BUCKET
            Value:
              Ref: ArtifactStoreS3Location
      Source:
        Type: CODEPIPELINE
        BuildSpec: agent-event-viewer/hosting/buildspec.yml
        InsecureSsl: false
      TimeoutInMinutes: 60
      EncryptionKey:
        Fn::Sub: arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED

  AgentEventViewerBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name:
        Fn::Sub: AgentEventViewer-${AWS::StackName}
      Description: Build and deploy Agent Event Viewer application
      ServiceRole:
        Fn::GetAtt: [ CodeBuildRole, Arn ]
      Artifacts:
        Type: CODEPIPELINE
        Name: 
          Fn::Sub: AgentEventViewer-${AWS::StackName}
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        EnvironmentVariables:
          - Name: BUILD_OUTPUT_BUCKET
            Value:
              Ref: ArtifactStoreS3Location
      Source:
        Type: CODEPIPELINE
        BuildSpec: agent-event-viewer/buildspec.yml
        InsecureSsl: false
      TimeoutInMinutes: 60
      EncryptionKey:
        Fn::Sub: arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED

  DeployPipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name:
        Fn::Sub: AgentEventApplicationPipeline-${AWS::StackName}
      RoleArn:
          Fn::GetAtt: [ CodePipelineRole, Arn ]
      Stages:
        -
          Name: Source
          Actions:
            -
              Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              OutputArtifacts:
                -
                  Name: SourceArtifact
              Configuration:
                BranchName: 
                  Ref: BranchName
                RepositoryName:
                  Ref: CodeCommitRepository
              RunOrder: 1
        -
          Name: AgentEventProcessorAndAgentEventViewerHostingBuild
          Actions:
            -
              Name: AgentEventProcessorBuild
              InputArtifacts:
                - Name: SourceArtifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              OutputArtifacts:
                -
                  Name: AgentEventProcessorBuildArtifact
              Configuration:
                ProjectName:
                  Ref: AgentEventProcessorBuildProject
              RunOrder: 1

            -
              Name: AgentEventViewerHostingBuild
              InputArtifacts:
                - Name: SourceArtifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              OutputArtifacts:
                -
                  Name: AgentEventViewerHostingBuildArtifact
              Configuration:
                ProjectName:
                  Ref: AgentEventViewerHostingBuildProject
              RunOrder: 1
        -
          Name: AgentEventProcessorAndAgentEventViewerHostingDeploy
          Actions:
            -
              Name: AgentEventProcessorCreateChangeSet
              InputArtifacts:
                -
                  Name: AgentEventProcessorBuildArtifact
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                ChangeSetName: AgentEventProcessorChangeSet
                RoleArn:
                  Fn::GetAtt: [ CloudFormationRole, Arn ]
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName:
                  Fn::Sub: AgentEventProcessor-${AWS::StackName}
                TemplatePath: AgentEventProcessorBuildArtifact::packaged.yaml
              RunOrder: 1
            -
              Name: AgentEventViewerHostingCreateChangeSet
              InputArtifacts:
                -
                  Name: AgentEventViewerHostingBuildArtifact
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                ChangeSetName: AgentEventViewerHostingChangeSet
                RoleArn:
                  Fn::GetAtt: [ CloudFormationRole, Arn ]
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName:
                  Fn::Sub: AgentEventViewerHosting-${AWS::StackName}
                TemplatePath: AgentEventViewerHostingBuildArtifact::packaged.yaml
              RunOrder: 1
            -
              Name: AgentEventProcessorExecuteChangeSet
              InputArtifacts:
                -
                  Name: AgentEventProcessorBuildArtifact
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              OutputArtifacts:
                -
                  Name: AgentEventProcessorDeployArtifact
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: AgentEventProcessorChangeSet
                OutputFileName: AgentEventProcessorOutput.json
                StackName:
                  Fn::Sub: AgentEventProcessor-${AWS::StackName}
              RunOrder: 2
            -
              Name: AgentEventViewerHostingExecuteChangeSet
              InputArtifacts:
                -
                  Name: AgentEventViewerHostingBuildArtifact
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              OutputArtifacts:
                -
                  Name: AgentEventViewerHostingDeployArtifact
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: AgentEventViewerHostingChangeSet
                OutputFileName: AgentEventViewerHostingOutput.json
                StackName:
                  Fn::Sub: AgentEventViewerHosting-${AWS::StackName}
              RunOrder: 2
        -
          Name: AgentViewerBuildAndDeploy
          Actions:
            -
              Name: AgentViewerBuildAndDeploy
              InputArtifacts:
                -
                  Name: SourceArtifact
                - 
                  Name: AgentEventProcessorDeployArtifact
                -
                  Name: AgentEventViewerHostingDeployArtifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              OutputArtifacts:
                -
                  Name: AgentEventViewerBuildArtifact
              Configuration:
                PrimarySource: SourceArtifact
                ProjectName: 
                  Ref: AgentEventViewerBuildProject
              RunOrder: 1
      ArtifactStore:
        Type: S3
        Location:
          Ref: ArtifactStoreS3Location